package patterns.sliding_window.min_window_subsequence;

import static org.junit.Assert.assertEquals;

import org.junit.AssumptionViolatedException;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.Stopwatch;
import org.junit.runner.Description;

public class MyTest {
    private Solution[] methods;

    @Rule
    public final Stopwatch stopwatch = new Stopwatch() {
        protected void succeeded(long nanos, Description description) {
            System.out.println(description.getMethodName() + " succeeded, time taken " + nanos);
        }
 
        /**
         * Invoked when a test fails
         */
        protected void failed(long nanos, Throwable e, Description description) {
            System.out.println(description.getMethodName() + " failed, time taken " + nanos);
        }
 
        /**
         * Invoked when a test is skipped due to a failed assumption.
         */
        protected void skipped(long nanos, AssumptionViolatedException e,
                Description description) {
            System.out.println(description.getMethodName() + " skipped, time taken " + nanos);
        }
 
        /**
         * Invoked when a test method finishes (whether passing or failing)
         */
        protected void finished(long nanos, Description description) {
            System.out.println(description.getMethodName() + " finished, time taken " + nanos);
        }
 
    };

    @Before
    public void init() {
        methods = new Solution[] {
            new BruteForce(),
            new WindowPropertyNotReusable()
        };
    }

    @Test
    public void simpleTestCase() throws Exception {

        String[] S = new String[] {"abcdebdde", "cnhczmccqouqadqtmjjzl"};
        String[] T = new String[] {"bde", "mm"};
        String[] expected = new String[] {"bcde", "mccqouqadqtm"};

        for (Solution method : methods) {
            for (int i=0; i<S.length; i++) {
                assertEquals(expected[i], method.minWindow(S[i], T[i]));
            }
        }

    }

    @Test
    public void bigInputCase() throws Exception {

        String[] S = new String[] {"cnktshvvjnnwftckuerryorwnpirtxjgvzxyfxmnwtcrwdycwdndcguzzvziachknezyxsefcxdjnmncuzgeosxrswnkfsoioezgwwnhkfpruwvleohnhgdcrhljvuxovajjpznmemjefmzxcfycskqwiqybpjzqdnqgvqaaxfhobugozbccxlvzwyedqcdilzrqaxqalggwjoyzexdtxadjbtryuxzhplvihxewahnldiuvvfajnmtiwbrkumvepnwvufxhbwkravnbwhjtgigngxohbtuakxhftttyluatnasevhpxcgiqertakkldcojqyvqwtbowliufswqfzmtcgoaejgnwtwobrskkzbmsspcpveqrhfertkeitdomceozpdrfeemfgggzwfywvlovkpsxwhmgfhlqjlkmpraerxlnmkhjciziivtrvbduapionqlmgbgbrmpavvsfvmbgtczxitctsuqskkmfcsrmvbgoygkawcxxccpzefzddtajwnlwjvfvhegwyforoymslmynhexdvftlhvstybaboduqcjwcrbmtonvdfvjthyaukrddvvypdxbavtavdzlzejyayevkneupnafnvmdekmloeowmrppvlzpdtoszxqbsbugmjjcorsvmbcydzmzegoypqkfsjutadgdthbfgxnrnqacmagdmmhqcoxdvsocmwdopvyfsthczdyzxnrpdysagsuvecbpodjsvgfyohcotnabrnbbtgfmvlkxfietcpwiwlwloxskwfesezaozkdmwqmccqstctvrmijxsndduiqphtkbqnhmimfmfigkwanhglnvegxpswsplscnumykeyeeguvybhjqsalaajpxuucglrsxuccuussnlgmovkwpclajxwqpekpsklhhnmcdpdtrtmlyxhwzebvesjjgirfpvwyscwgkesahngjahacftxxoyevubhxlcsrpyxjwyyzdgsavkfkmoxrhjzvnquutgncyedgcmkhlomkdjjhnhbiefgnnyiqbhzkwfefgnzdyuhnecwgeqimempikgswvhnfewstpuvxwewgdlmeeicqqifmsxjjclwjsjctkeveuqfryqyuvahtxybgdufvdtaefnvnrooiofmesjypuegncrtvqhxussokaraopboqnngqebuueolxulrmwfdihjplfmiottohagheohyhsndmaldbupcqiflsklhhhubmpybgzggmsjhrhydjzgbyeljdzxlkzzdjqfngetkvkystbcetaxmycdsygtwvjvieehtetvtelxhldbcjnuawdoepicnitdymznrykpmpiexquobsaqylguwbdnulupzuchkxfpxrtjmecuckcigucggzieergyxhfmuiaaudnebsjpcrekmibkxylejpcmcmyivavsnbzoairaiafvikymdndjbqzkbdpzbenzhtnloqqkwtsvchejngxravpfwmcppdkoxsxcxwwursdcpqxrcbbtkammzpalutgkhlfegafzfusbtfzfdlpeyljiaqqddwtopkjmpllfacqwckirhwiqudfomcbhhroftcgrlekzmxxhhhinqwayyjbanmekzagyghkhzkmokhoojotfnznamekmhqptnkkqzcalhuiqsnpedcmowfjkyfhqjpsuowwrpdgxqcvyeuvijckhkoxeslqzexovcliqkkewdlzxveurjycsjrpubfxjcutvmniqnzdakwbdrwxxnmpzityozccozzmrunjgzryylaqpfuqxaqmrzpwjcfgscupkavzrocuizmmmffgzselluxhrgzizokacdsoaovdbeovbezzvrdsscofwkbiasytokpylwxmroekjyodhlulubkkjuxtcatmcjknpjeeuuysrmtfjvduqyifvpcjkcqoobdpdtcvsgtkjfghaelzpqytixemppcqrkfhwdilbkurywafiwbqeywcqyniypdxgcyfhkmmnnycaonwgsqwwswkkjkkofyjxiihaeswxjlglcmzghxdjvkhadjxatyqcsvtmvyrbjadlnvwsrmadgqnmkxmkoqfiydubdzxspyygmjiaorkfcxlsktcqtwojngoxfzjjdnupbfvagukavprsseanygyhywtixtxqochiiizchyusfwzktfwgcuvfjgcwqvwgsdwkodtpphxxddtdzionwqttvrsocpkhpgljvhdzgfmfgirszfpignwnkrxuccmqcljpdlgaxnfiaeeadrkqxegfedbpnjnpyobactbjoqfppkhiicohesrhjunplsmipuhxfsaumeqcrukxhfoacvobqavodstisklsxjwqtfbhycmleycdomvakdkbduzwksmgfjcdansworblcpvnzzfgzpmelictpyuqchonlduzfltlbskpfqrisshtaambszqqergfeefkvkiogrgwknepimwoqoxbdjdyisxeocdjocqqqcxemiuzzburlxzogsjcylrpgsmqgwzyynvxjxglfyerlfmzogaznhkkspcsomvvixpukzifbflzkcdfmeaxvwuhxszzmdxujtgqpphnmsuhjzszvsnvsykuokzwauiytajvohmmmwbyikmzwpcyodaxdonkeczgcmedfkoafpnclvhspddcpycrtlvqihxvtefrwmmkbpujccauhdsnlidiekgnxgwiwbimrdbwxqdosqoczluwzpaiunibzrewyopculgbhzjxqzdqgrfkrhslxvdvxypxaxjphqcoujfkalcfjopujlgowbsoctvqxdlkoceyngwtauwxcivwezgorjnkwacuyvyhlndztnxkqwflmqyoxnhtbzfzsoglazflewfqzixlvzmmrmihuexgehifhsbrvqeafdmjixgrzqsxppnvlcrmzxoufkfihwxkpimwwcdlldvdifigzfqhknxqmbaqdriyoztlniywvgjvcoaprfgwlwvwmddsxtlzvxhhmqhktlpmfdtiqnzbpqaclxtddwhpqdnkswoldhgcldcuaxvtieygsjmjgokfmmyfxvzryvluovavzhobgwrmkceqayvkwsvxtksqqxgfgadazgfmhgdsxjqakcuapfqggoumfoqugazlvnupwneheathmofbsqqilrbyvcnejjvknktenkmwvzocyrxwifjhrtkkvvyhloqnjyqmiaarrunwpxlttzvgvbicbktedyxdzwdooghxapvydbxiwmgvykfoylyxvxajpjemwvgygdeddwlzzdvyfnhqezhyqrsxcgvrrgworoynclzyjqpqovlpnjvqcluhjuoubsowraehpjmlpdnxeeanoikvynzejzijyupwxclupdpvbeqjkamfppjbirtztttajigqpqcqzprpwnclczpqoqvtpejibqdurjmhlvfongstxjyinkpbvlxplufjefpirxivjusjbexhulhvzhmsvorlnsulffysovkljqsdkrgpakozcdoneswhgwmdkzfwanjegxzcxlsnwzqvwqdoezufibpmgeuilgnakundeskyiddhskgdkryhnjxcmujlytukhypquofveiwqwaylrlgqyhmyrnckvdlekbguphwuajchmqwialethmfpkswaqfbdxporwqjluaemxabukwamajjrcoapuzpnnbleapcaqonxnbhfbbdoffbhuimrawgdusrkvpbpbmrwmsprxfqjerovruewjixyfdxfsyseolnztyusbtzfnlcfygpwwogystbtrddqcrhoiqvmrdzglohzhsmwlvfqwtrdvspfvofxaynenoaivxxcpuzeswdzqjxknwdrrlronqkfaepmqltdeiizhkxkqeohexggdrfegsiwjzipextyrybgttgghfbgfhjnvzwkpipguuevqwwjyyjculvkxjeiwhuowbeofmsysbsemjlrnejuonsofjlueexsgsupmrepknjtvrgbczzdvphfnsavcikhdlrycasxhfjaktukleqkaqybljrypkajbrhofpqsqtzuphixogloroidliepvzwnufaacsrzedslnbnauermotqhmstthfavourpvxrtwejmhdtlyhghtcdtkjemumbijzwbuervgqnhdmmknfkgcefnnjajsrqnwqjligdgwshgudwtswrdnfzrvqpvcjanvfbkaoykyzvjugwcdmyxzjxoynuuewvjqrvapfcbulcaplshpgvjithcvvklszenadnkejwkwzmzuyqmedjhgaongcowisexptzhpxbbqkslbccgufgkivrvgnbrqbeznbbxuybpvsbsicppjankfeiporftbmuhrsrrpfnqnresowwhffzffgguvkeddbozcphysxxdefilnmttunvllswisylirrlhszrbkcxefsvchwotxiwhbpzhydkmggcqjuwftskjyluvptnxegkzauezmvmtstzhphddittnsbrpsnedfhkaeapxwfyylthmguzrwezispcqnsoqyxjflkerbepjuisfriqqccvzjgaddrushpywnhirkbrcdvlhnasatsptfhrwymunnkhljvnopauzsxwxgywrzpndnvbizxzrblgngiztotethumpgkyrgtsqpzhvsbrjwbmmfzrdwlromamktqwjmikultfcpxjhilhcfzvqzkqpsjmqlmkcmpeuihxcgairnzcxctxvpljdptusylasvgzovqlpnpgqzvwszcxfgbdexyjafozrgssyqgzqpesprxdfzwtzgzbygohfpwrnpsbixqoqazakwkfphooqjdwgbgznqcgseshaijaymuiibybkfgtefiudqsnmkakykisyghdkqlsbzvjvygkoqfjojttetujtwmjweajqanfxkrgatclvsiqgdvxhabgaosnppauctcyokyiduvolewrrejwcfwwfpsrojylqqmghgyqvfvhffyxmcxrukmdgkbjtvyuddlidchdxfypteagwbwpurzhuaunainneqzvrbesvnynvfdcqvkrlkoedzcckkhdujfosntmnywzriwzaabkwhrifaofxzzxusscxzmyilpopaxrrrhctlhsecabzyasbaiqhwbhmmejvvutshybsfaqlxcvefangxbquzdlioobhfocjpitdvbzhtpgtdbhdgnpgfrfpafawwwziysbdbmzkwvulqbljqlaanshfblfgmrghropzawtxeprrqaoyegljjyekfapaqhpeoymjdpagxszetwaewbcycwmxmcriayniyzlwsnziifaysianuoygbqhubeqfjymafzeoxmawxtdxxbaobmfqdvdpkjgzhtdclfbrfwdrzstyhbukqjenudyqjgsgthgzpipizpaowcfiiafwflgltxzpijoytocluvqlmufbqxndgrtvkaktxlzllefzhnizdesmbmqzjsefwofwajcdawkqegghrhkxnzvfpskthktbyzzcbotfdvvbwdpiuskxuqujakrmnxafgrahwcfpoesbtlnuzoktzvezsxkwnxxnqlstaagjpobbdzzdzlfktgwdddemucejffgqpbisvdexpcegijmwrbtxhrimincyamurnfnhpoaupiokjhrgsrtbdlmmwypsvpzdyltkzbaknxcwbabnebrwpfaldigxptxneyiolkinegfkebeakontlolhytbdobtzguyjvzahultyysxuilxffoowovcnncwfvqvxvxjjkadsrgdivzeyfvbtygjehfirilrivkgqkagayotmyjniwhxpmvfnvkazfophffofalopxdvfuyozfzbswynuqhcnnnjnuonrojcrjbdpebvgueyvmcrmmmkrmiiyumpavhyiktejbucgolihtltpogtgcvrryuttigbcegnssfvrnnudyuheyserppzvzncfgurdzhezbadbpnniclevsszmhjnkvqrtuvuhawjsdjluodcwzvcitfcydtaxljjzttuwyufgumtvfohsqwhqlucrnlmkdnvrjmuufscnopcbaadtunhpmfhrezvbzgrgavpgzecdrampabbzwzutfjaxekccifvwbzposkmowhrggdbplpwxqdkanxltrxwakafvsmkldmistnlbtiphwhqbrkgrehxmkuartsnjklndncrobiefwxkerbyddpcymrjpbbikvtjgjnpdviljxywncccbyajkvhtnvybaetrqggdhvuhjqwwmnogvyctofzvavdnhwyrooevdwxiehztywcpaktimvvimrwqiiuiahjedvhcfmqvseugksfwququwvsjewjjxxehmgnnmunfhuvvtnlpeicojfqlxiqccqplzpbspruapavyxehvvhhtldjdvldgqwhxugrzhpibpyvhdkqkqorworgwdnzjqnfjcjqeciezzlvhygzwwllkuvsmahxfxvysqmjeltlqriibyqqsxojypvaeeobpzmuptccqcprpomxmtzjgrmnsnhqwwxhfxfcdqskjleisfgoqjoedmisahrdlgkmmbvrgljepgunaqctazghpmacembrbiepypyevwpfsodklhtpuohpwdiulbsbrsajzxdbevswppaulfewmshvvjmkffvmhtdimfjymjsuycjrwcgzbnsdmftvzraelvhjjqbbzduyzygqnfdfoyhzfltogrihfjnjpilwmdscecjolzkkhxjzxnvpjeamzknfinzzwniwqxqicqpxndlrprudfylbdxrqxqrgttyeijosqwewcuiwszzthhvcakhqhdauftuhjlrnkplynewxokycgttfkhhjorgxurnqgkxgzsinawnxszeifbpkrgbccnhnrrgzemtrbgzqduxpihcspgxjxppstwxzpymvnzowceagwdkvdwuhclqdpvufolmuhsmhwyvjxgpbxhiiayyatnujbcxmutxigryedxbwzpsjlwuvwxyiramufhutzhiblaosvskxgnhusjdhgkhcgahzutilyddnhqgpjvfjbvmselkbnfkhmodcrexrxbhgehbdustdnlgyicgdvcncmatiwcindbhhhutuayeoaqyhohztiftlhzkwjqdfiwxiltbhwjrrywcyeqgyhexeabwthtazeqzxzfjpfxgxnfyblmfgydtlitudiehnjhqbarsmijrcxkinycdkxmrsupwitonxvsirbhzuynolbbuzsfpgxnzsndmxjvqkvllcufrdkzjdgrdoyqqjxsgxsulfbbpwhggeerbsrrlzhtecjkrvllfwhzgrnhmtwvfiyzcuwcerbiuuidrgbaudrfklwhaalnvguiheitidwgjrbntdoyeuawzegcobnbetzjlzczgstoakfwwulruryadzsaoqqacmtbgrirledcnqicsmirincktndneimctlkaddlbflsrhiunnpoercwsburefswuhmrqigzaibdzyxnxvncyonlfvwhnyxwfjmordshdcqgysbqpqezevtigexnrihwygbuokniycnfloaltnkslhoakqrdkrxsdfcleyfftoitmpprkwsctkyxfphqlrbramofjzaxoiylmttaaoizgoqkxtpervzaevsulmfhnjlttctxfluwhriwcvrdkktfxsplojdrfpwxxvslxkcjoerowlcdvaozxexumcxovvbkozaeibkqlvpdhdruscqjzecyuevjvntmasjuxivkirytoynzghicbwckthidofsethngqnujwznvulhqycbuptzhydqqpbuygazggzznxjebfbuhsqzbjbhcfizzflptlagdbywrkjnfbsfjivfptvxdvcwehmkvmqiiqwsjvsdjitfixcabixbmvuxdmnjfdkqrqeymvwpdjvtlworalfxdtspmiihqdbhsuywnpkbxipdpjgrageuxfzrnksjfuogoelguesqhzoxuxmtlylknsgeazkkmzxguanriktzajslmaihdnpxauhijbufkgbyxnovexglzpzdyxmjjxrmbofyhnwbsmcrodkfamdvwzxnjamizveiaopjswwgvtnsgkbjjlpgvsuzgclajsxypscbrzdrkkcanziqggmncalhiqjakhlkfydplkojqiletisbctfzcphibuctjavyuqqrmcbfjbtenzqckmonfpgqtujahwjyulwxymaflvlkcaihphxltizzeictzjjursggitwedoniejfltmuttsgbyxfniysjkenvuasmoelrhumytjlhvgckgquhzwadoqvxajhjaqwurpprsjgqxhyrxnamifichrjirtzbxwnadvqqzoviryzvseqppehtlbumdmfcpdmcszhxjvluevhvjmsqwczrbfwcabhrsgjbquxufbyxjhbjzzpmsvpwskwhbqudjvcaxqikgynalewmlvbzugsfbwaiwkbpvszkgdjvakzzlsglevvscbmpkfsqemtqjrilkjrqxkjvsnrjcfiigyymgiosobwfkqkmayrrslfjuomhjjkvxpeuesctafwrrhfnupzxhlnzkuqghswcmpehttqngiqndfnwbifdzayvvfombqoozuhmbpqpvkbkdlmmqrmtdxhggysjrcsmlgplakaofzpmbcqiebdaspocflrrslsihrfpsvmloqnqlxbiisfdpmazoscutrjnwmjlsdjzzhidtyscwjfflxtttnyhnxbdjxetlpyvxpzlphxnpesmshypxuxhsfifzkrlzvmblucrdxkpgtnesqxiqrbrgdpezjzzgkrvklgybtyllgtzwqnqpdzqtdcljyjrpbcapqpnkfkqplqpovmksouksntnpohikxlruuoqtoykdsjsadhvnbtchatstrverslajctxshlfqywvivsndbjiswjafwmbesdnazzsackrixiivlxzksbiljhjgbhzqhxxeyxvyjqhmyskqxoezpmclxvuewdjicsqbhpjsslhtsexjxpzfieskjpweilnmcfoxxmnortmjqgbiiuaqvzxcijvxloibamkwvumhkblbqxcgajlkjchtxywpfdwgxqumyawafepcjbaduiiodzjitrqquqfwhnibzgitnlchftaatojaqaqknciaddyanvouqigxqrrsiskljdheqtimwzmdbweccdkibyzhayshykyrfbnbiylpeozcjhostzxcdgmwcfhrfxlcvomkuztsoeanzwrrwpilttxlemxcxgrgibglvwybjuualvnlnpmhpydfmnbhpgnpisuxpykznsexcfctncsiwdokdndartxguvfgxzaepdrzkwgzxglxpaccblvfobtnhbzfyuwofyvuhudwcjcxtgeguztutsnentivkbbovrogoqtxlhcqsaljhzddbtsjleizzuqsgkhhzlvbyhssaxhvlurxbtzbquzuzrqysvgoknchhzfwkvetulawwbzqjkenkufoyviahmoubajzopkewonxenmzpjrzunfislubrvwwhmjrkmuuqafkbzbhwobsnevqeoglgpatmvrpnzqdyabxmfjiyimqitpxnejdgwbgmdktrxnmtlvzasbrjwlealyvsntxhqounrbfdzkamcbygtpttgrnrjdtozapwarmxrvpmmqfeixdgyscieurckdagvolfjrzcjquwlzqhchzyykjwrqjtbngbjlacpbkevqobcieqmuovjgqbomotarpvikdchonhvqltnjgwiqifwxvkdmmmgaozzokxbtzmaadbuvmdpeaphvoqebijsqebbcbzltkjzvthhukobdtxoggyjmzwneeiibsjvzsnevcdevdfxinjanwq"};

        String[] T = new String[] {"ereswethisxakuwzddblzcgpmkbzwnzdiayqlollxctiseifmnpdhacvotczgajpcklgsnylkseejouzhafykbwlnpppwmocybfg"};

        String[] expected = new String[] {"eazkkmzxguanriktzajslmaihdnpxauhijbufkgbyxnovexglzpzdyxmjjxrmbofyhnwbsmcrodkfamdvwzxnjamizveiaopjswwgvtnsgkbjjlpgvsuzgclajsxypscbrzdrkkcanziqggmncalhiqjakhlkfydplkojqiletisbctfzcphibuctjavyuqqrmcbfjbtenzqckmonfpgqtujahwjyulwxymaflvlkcaihphxltizzeictzjjursggitwedoniejfltmuttsgbyxfniysjkenvuasmoelrhumytjlhvgckgquhzwadoqvxajhjaqwurpprsjgqxhyrxnamifichrjirtzbxwnadvqqzoviryzvseqppehtlbumdmfcpdmcszhxjvluevhvjmsqwczrbfwcabhrsgjbquxufbyxjhbjzzpmsvpwskwhbqudjvcaxqikgynalewmlvbzugsfbwaiwkbpvszkgdjvakzzlsglevvscbmpkfsqemtqjrilkjrqxkjvsnrjcfiigyymgiosobwfkqkmayrrslfjuomhjjkvxpeuesctafwrrhfnupzxhlnzkuqghswcmpehttqngiqndfnwbifdzayvvfombqoozuhmbpqpvkbkdlmmqrmtdxhggysjrcsmlgplakaofzpmbcqiebdaspocflrrslsihrfpsvmloqnqlxbiisfdpmazoscutrjnwmjlsdjzzhidtyscwjfflxtttnyhnxbdjxetlpyvxpzlphxnpesmshypxuxhsfifzkrlzvmblucrdxkpgtnesqxiqrbrgdpezjzzgkrvklgybtyllgtzwqnqpdzqtdcljyjrpbcapqpnkfkqplqpovmksouksntnpohikxlruuoqtoykdsjsadhvnbtchatstrverslajctxshlfqywvivsndbjiswjafwmbesdnazzsackrixiivlxzksbiljhjgbhzqhxxeyxvyjqhmyskqxoezpmclxvuewdjicsqbhpjsslhtsexjxpzfieskjpweilnmcfoxxmnortmjqgbiiuaqvzxcijvxloibamkwvumhkblbqxcgajlkjchtxywpfdwgxqumyawafepcjbaduiiodzjitrqquqfwhnibzgitnlchftaatojaqaqknciaddyanvouqigxqrrsiskljdheqtimwzmdbweccdkibyzhayshykyrfbnbiylpeozcjhostzxcdgmwcfhrfxlcvomkuztsoeanzwrrwpilttxlemxcxgrgibglvwybjuualvnlnpmhpydfmnbhpgnpisuxpykznsexcfctncsiwdokdndartxguvfgxzaepdrzkwgzxglxpaccblvfobtnhbzfyuwofyvuhudwcjcxtgeguztutsnentivkbbovrogoqtxlhcqsaljhzddbtsjleizzuqsgkhhzlvbyhssaxhvlurxbtzbquzuzrqysvgoknchhzfwkvetulawwbzqjkenkufoyviahmoubajzopkewonxenmzpjrzunfislubrvwwhmjrkmuuqafkbzbhwobsnevqeoglgpatmvrpnzqdyabxmfjiyimqitpxnejdgwbgmdktrxnmtlvzasbrjwlealyvsntxhqounrbfdzkamcbygtpttgrnrjdtozapwarmxrvpmmqfeixdgyscieurckdagvolfjrzcjquwlzqhchzyykjwrqjtbngbjlacpbkevqobcieqmuovjgqbomotarpvikdchonhvqltnjgwiqifwxvkdmmmg"};

        for (Solution method : methods) {
            for (int i=0; i<S.length; i++) {
                assertEquals(expected[i], method.minWindow(S[i], T[i]));
            }
        }

    }
}
